apiVersion: ENC[AES256_GCM,data:ToY=,iv:eI4saKVqwPjeVUXZfqIy+9XSbAjeFuXrgNked64CG40=,tag:KY59ij0BukBX0LwoFgALKg==,type:str]
kind: ENC[AES256_GCM,data:FFfH6J6x,iv:D8DCXw4b0xH243EIHhC6nYT1PWOPDf99LfKL/YIafN0=,tag:aav0pvvQE4T9eHy2dgkEHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0Y/pddOgmyVXK3c2jgdZz0mGAZNhse1xRe7g,iv:QMdk73oTct5wwh1lkkHlZ+GPeAfRL44UQHNz/8kX+WY=,tag:jAOUuQ+5bCAn7t7uVxe53A==,type:str]
    namespace: ENC[AES256_GCM,data:CjTJ8rW4VkDv277G,iv:nuiYwPCeVyuIrQaSLcDaEHrpu69oXWIpNKc5eG6/SRE=,tag:htVfFwfuyVj85MPT9wbjGA==,type:str]
type: ENC[AES256_GCM,data:+vp0A3gH,iv:3ZOcOnvymZZ5YQOc2EgWsrC220lgPIAEn9d5oTPYuYE=,tag:esrEuiBGtXA8PYYtFJi7JQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:lGMbKfxXh3crhppHh8KeGJf2/+zSiij9nQkmeYnic8vXlA==,iv:Ob/3D10LeaN0ny74X16nixAScHMQErXBhRtNnvhKsHI=,tag:UaSXMLJXPcqJzyduvbgVag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbklTNDZ0TlBSa0JHSHZ3
            UmtYRHlIU3lkWU9mZ0hKNk9McHlMdzVPMFRFCllDUGNDdEpQTnczMDMydHpwT0lQ
            L21ma3Boc1U2Um5yZmpBZ2dJTlRhbFEKLS0tIER3L3BQWEtWR3A0ZkJ5c0ZVSDlT
            NFVhWEEyTTNjanA1V2tKR0N2MGhuZXcKzBQA/lVar/XokvH6pqakTXzVYiA2WOCl
            pTNXJV+zrxgDGYMjUaUI1Nfxc5imLPQqHnie01LMMh9i7w07hksluw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T15:27:16Z"
    mac: ENC[AES256_GCM,data:1uquvJkpQhn6PAtLn543pknmzAP7SJ8Sid8Id1e8SfxoytGdDIY8BQc4UhzbYQS4Cb/QpN0cGH66DjWqYh9EFMyvSD56bbrz7CcGCD23UAgIuk/BSH5mZDNN/7mkE1jdiyZTP6vfMDOcbZ7L90qWcGuQsUC8MMEL1kBJZ317KNA=,iv:3VJsh8NrZpMLOX3cX+TqBdi5/0CCdsORu2SFzAy670Q=,tag:06nNSVKWLPlNio7WMFV2xg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
