apiVersion: ENC[AES256_GCM,data:LyQ=,iv:U+Q/eTQlTtrj8Cs+JIdyP/gYyR3ile1ziLobo0h6k4k=,tag:IZLFTziEenzmwBvJ5fZNpg==,type:str]
kind: ENC[AES256_GCM,data:XQu6hRed,iv:YBvQ/q8WSCLvlxfFFzFH03kAu6o60YZVDjZDTdHme8U=,tag:e0LC9DWJ1aa5yZJCeL3a3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wmW8Yk75yBRmSHGstG0=,iv:fybyhBZ16dW9GbqThTjlUiLrw5iCMirO0bRrhICaGrM=,tag:QqTk7nr2kJZYILa9JZOBQw==,type:str]
    namespace: ENC[AES256_GCM,data:wYbcrJ3a5A==,iv:T8PONhUIt42jPGAiQ+Ua7mE97aTF8JJEcBpP3ZyPQ3Q=,tag:v7ZmP0Qd7TBk1wsnj9/MPw==,type:str]
type: ENC[AES256_GCM,data:+VKn+NYw,iv:Zk3A9LgyEIRvHHwBXL7pYZBnJPJ+uuLVsJSsYQvK91Q=,tag:bUiHSYLdr+jSR9NW8vE5Pw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:8pABYzlQ0DXzyXLhAvDFcnrAgZ4TVguRfg==,iv:C3EXoZtQx/yxwZ21ckGSmQYrUONiLUT+yNcpkOpkyOo=,tag:ZCGXljHJy/z5LzzTQkgOfw==,type:str]
    username: ENC[AES256_GCM,data:BiA40VCzDQ==,iv:lt5eOiQv4QX0kCGKadH4VNjRqBjRY+YYLkY0pemtx78=,tag:o9HQbKsQVuOS/tM40okmFA==,type:str]
    password: ENC[AES256_GCM,data:UvafW4WmTNAL7LT5PGpxxIPTATVLT+CjYQ==,iv:fg60Sd/fYGm0JidHvrWYUBckcp/YIOtzBqo9eXDYK6U=,tag:kxhvnBeEW8UuScF2u2JwBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMHRMdzFTanV1bzB2VzVK
            bW9xMkhhci9nZGpEcjdjK2Y5Q3NiNTNFd1dJCkpBNzcydEczcnNCNldReW5MQnZT
            c2s4bzJ0U0o5Vk0rZm8wcTYwMCtrc0EKLS0tIGZMcEtiaEdHcEVLdG5JdkN3V2xN
            RWRPVG9jY1pnSUNqcXlBT3dOVmJXUjgK9yb87VAwreOq7m2m/fybzPSBy3XsHpDS
            ZDjh7HOWrc2j5AsDWHtEwyXuK4nqBPbwMnrAvqqvefusB5zmvLcR0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T15:07:22Z"
    mac: ENC[AES256_GCM,data:lPLvZH9kuxwYO7E5Eqsw3ZEA3nSaN2YACdWOyRW0WN5Vb+SmNhxdQn/sISp4tIe4rOJaTpTIlwOazt/LktZooExp1QAyJ/pVfQ3DNNOnuRBnaE6AqNKgQ2h88UOfq055IJhslsFQrWn3728GnJ2RF5trBFbZUJI534yPLtFHu/8=,iv:gFvshh/sK7IFu0iLVDft+KHM/jhgoA0kkmlhtvVNiRY=,tag:XXwdm467cPnYzPdSneEjsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
