apiVersion: ENC[AES256_GCM,data:w/w=,iv:JvyVTQTC1p4nn62OSw594rWIP62tAVQi+6UUr0uZuXY=,tag:Oye0cuPCjKy96ix0OhZPeA==,type:str]
kind: ENC[AES256_GCM,data:CTF4WZA2,iv:8pOhVn1MqkYD6E2xPIcdhoI4qKz/QWkPtqOPBU6k8Nc=,tag:4TC2zetJFQSWn+10LfkWIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AZccJ4FsQXjJ/N60WpdxDeg=,iv:zozvr6I7yEsAbGbadWsZsVYdndgLhhPi/zPppVnUM3E=,tag:dzjTVwMSEONlqWuMhYcosw==,type:str]
    namespace: ENC[AES256_GCM,data:jKQIMiA2AHUh,iv:pGISsvQYdLFxSouoSPTpfmnT8TSEMxJbePw28KLZR7U=,tag:CFExuvqWb+6FiEXfdaSjIQ==,type:str]
type: ENC[AES256_GCM,data:AK+bZurq,iv:Ea76vp0YGilEapjKmpEjq/28u1iKMoiQCvr44iFXCRM=,tag:OHWX+1AmcFgurhRwmSDnPQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:B7ps6WQxoc5EmfggKwg2Fwz5zQXSef3bVg==,iv:wMEBKl1tWXCtRGtQTJB20WEZdnQYaWeb8XdbR3UWzFs=,tag:CsDaehg7putpYzTCBccIBQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:FtSaHkTClYFCq+wazxwbB0yAht4Rt2p3VoG+5SQYN6eTww==,iv:zCByVyDA2eJAYZpN4tdz0mg3Mk3lFmuYUF55eLpmTzA=,tag:b6eVYoeNHY798tTQYFi2jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcXBPNGhhUFVJTGpUdFpB
            SVdoR0JBaFRHVUxRbFE4OW9CWUlSMWpJSWw0CjVxanFTRS94UzI4Vkx4SmQ0Yjdh
            eDJqTVgrd05PWUpRNThjbTIrWXM4V1UKLS0tIDUxa2ZUSmZiNkl4U3BSOGhLSnNY
            SEplWG5YNVo4R0xhK2RYNDJrb2pZMWsKFDskjZRnZ7AlCn8g04kbMRjDs6ugATTv
            LR4tHOyKHjdm8I8cYv/TtenPcfHhqp7Pvw3Egifr5QQJLh6DjJlUWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T17:53:42Z"
    mac: ENC[AES256_GCM,data:wA2FVtqE3vKAEzBgjjJl+n8QGOqg5k/VrOSbm1TSXQysoHAErsUedDE9Gdi65TAwYVShMabsf95PTL6tFkQFdLclKSvdCaMGX6ihf+E+uIbDqPrsqozE1LgR9EladOH1Pmki1MIQiIK0KY8FpJd0HZaBwYOzFzzeGbRubTN5kMU=,iv:ocqCkJL0CgWi047D1y2k96t2swbxSZiEV3B+FnjJpXQ=,tag:9y2vtJ/U4mIolrU5j2DfnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
