apiVersion: ENC[AES256_GCM,data:w/w=,iv:JvyVTQTC1p4nn62OSw594rWIP62tAVQi+6UUr0uZuXY=,tag:Oye0cuPCjKy96ix0OhZPeA==,type:str]
kind: ENC[AES256_GCM,data:CTF4WZA2,iv:8pOhVn1MqkYD6E2xPIcdhoI4qKz/QWkPtqOPBU6k8Nc=,tag:4TC2zetJFQSWn+10LfkWIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AZccJ4FsQXjJ/N60WpdxDeg=,iv:zozvr6I7yEsAbGbadWsZsVYdndgLhhPi/zPppVnUM3E=,tag:dzjTVwMSEONlqWuMhYcosw==,type:str]
    namespace: ENC[AES256_GCM,data:jKQIMiA2AHUh,iv:pGISsvQYdLFxSouoSPTpfmnT8TSEMxJbePw28KLZR7U=,tag:CFExuvqWb+6FiEXfdaSjIQ==,type:str]
type: ENC[AES256_GCM,data:AK+bZurq,iv:Ea76vp0YGilEapjKmpEjq/28u1iKMoiQCvr44iFXCRM=,tag:OHWX+1AmcFgurhRwmSDnPQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:FJHxGq4xJUdwjm/F1eEZ8+cbZSsJXeW+MzYkVSePnjKLpkzWI2AFX6QfqN3PChCGaBDd4csKHjwSpokvwMaBlq/HTAhV1RKa43PkAEMWXsk=,iv:uUxmni1TXxK4U7OacK86nc/7F1cpnAiIvYHNHj8slHc=,tag:scjJJ+569l/Gw4WQxE07YA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:1PrwmbwH5FMhE0YD2L1jYkVcsTX1IhtjVghhDezKZw+RneJ01x/FYL8jNoDlQnP+PLkGAnrORNwyc6KRHbI9Qw==,iv:lMltxPGhPJTy6/2uqFNDQdcHBW4s2+fu70q/XcxsNfI=,tag:lsuaP/xs85ABPA9ZeFUc9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcXBPNGhhUFVJTGpUdFpB
            SVdoR0JBaFRHVUxRbFE4OW9CWUlSMWpJSWw0CjVxanFTRS94UzI4Vkx4SmQ0Yjdh
            eDJqTVgrd05PWUpRNThjbTIrWXM4V1UKLS0tIDUxa2ZUSmZiNkl4U3BSOGhLSnNY
            SEplWG5YNVo4R0xhK2RYNDJrb2pZMWsKFDskjZRnZ7AlCn8g04kbMRjDs6ugATTv
            LR4tHOyKHjdm8I8cYv/TtenPcfHhqp7Pvw3Egifr5QQJLh6DjJlUWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:18Z"
    mac: ENC[AES256_GCM,data:Wv+daXogMNMjx8h0z2J/CDXk31UVKoYRFXBHZGzVvl7PteIvOPhmDRvi+uWs7vN4QPxG89aPAlSj2708HQlVmmQGKMjKbkZQXu7rGx+K8LSUitcv/capDiLDeNyZuHmLN0jELBAeIYukDIubEzNyz7WjuYku6Mbv7TgJDHW7XPY=,iv:/yBIGsM3DvZCxAnG4rQhKX4zg3I50GuG8cJvTS3+Aug=,tag:uAsYEAgWLHYS8pIuZ4XW7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
