apiVersion: ENC[AES256_GCM,data:uFQ=,iv:m9s5uJe538k59mJ9ybuK/2wmXtExpw96XVwhQJl9ptM=,tag:Tlm8/HuBfZYDtFtNl7/7Lg==,type:str]
kind: ENC[AES256_GCM,data:0/BwIsTV,iv:jvzme6r3WQLZWrr9ZxX0qcOYsuByVPLaiQGW8xrsDRg=,tag:EOulsGCtLs1Lkx+MY17NWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y1JmjTpmdSD0Lq7qKfhEEXSP,iv:HN1OiMuM5qQX+WmksiiabhAuUxbshCQ+gLNOB61sZXA=,tag:YBx9UqosjhdjbizkDPp7jw==,type:str]
    namespace: ENC[AES256_GCM,data:q3Bq0Skq,iv:Cwv75NUXvznLL8GBrsEkoMxKGdlRKijK3RgEUaP1vrE=,tag:DvaiGvjm9t2iS5hsrlh1aA==,type:str]
type: ENC[AES256_GCM,data:cbYQvNQn,iv:8WLgT6eiQDA8VCZd2+5JRdap7PvEemuNtEilimmmJ/8=,tag:mxoN8J7luIrjP+urXV/VqQ==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:yFdEVupU5aWHxUdLZRydW2OpTr0GoiC8AY9NJzw1KdRrl6sHgsoDhbk8X2OzOEqhaCG6tF/Qp1bFcNUVQVOXZac15sKTseatWZ+Dd4fn5UGT2V3XmN9C0ZoR6sC0Awh2Db85yiqTdbS50lR5VUtLrdx6,iv:NCUYmLxuMaW7HxJv3EiaiX3NOkSX8nbpMoeSabvuGgU=,tag:acPo8ws8H9x99QkVoEe7vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzg5MFFNQzhXMWdzVXQv
            RGNIQ1VLSkExOWRuZXpCRkhMQk9uUjJrQVVnCktjWDhoNGVVT21CNTNDS1ZGam1s
            L284NHZJTU9mWTFmVlA4cEQyWDVJbG8KLS0tIGdHRVBQblNvK3ZocWRPbWtRaTRl
            M0c3emtpam0wekZJN0VkaENhSXV1Y2cK/xc1c5nlf4NknIxaiMqxE+ygHLjvUnO7
            by8nwot5ZlxIqHu821ZAd+LM7NeXgYg1HZe0BiOx7WCxOePuj9NOYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:18Z"
    mac: ENC[AES256_GCM,data:2pxhDlFPjdvzLlBsUG0eYOO3yiY5PidjgqAyU+kOGcx95BkFh813SaK2xBsI8ksv7Utuiv2h0XZ4woT575M0X/ya+XyF/H9Hd0MLYgigtOpa0O8NtlaxTFfFxZHF2FffTdAhau0UBgpXdMJuM9hlMcgJ86S5Ha9jjpsHXv4GiQI=,iv:Nhqtd6c+lJyUseHkOsKfNKY9Ygqfe7UQrP4k1MDx1bQ=,tag:66N57b9y17f1i57L71xCvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
