apiVersion: ENC[AES256_GCM,data:uFQ=,iv:m9s5uJe538k59mJ9ybuK/2wmXtExpw96XVwhQJl9ptM=,tag:Tlm8/HuBfZYDtFtNl7/7Lg==,type:str]
kind: ENC[AES256_GCM,data:0/BwIsTV,iv:jvzme6r3WQLZWrr9ZxX0qcOYsuByVPLaiQGW8xrsDRg=,tag:EOulsGCtLs1Lkx+MY17NWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y1JmjTpmdSD0Lq7qKfhEEXSP,iv:HN1OiMuM5qQX+WmksiiabhAuUxbshCQ+gLNOB61sZXA=,tag:YBx9UqosjhdjbizkDPp7jw==,type:str]
    namespace: ENC[AES256_GCM,data:q3Bq0Skq,iv:Cwv75NUXvznLL8GBrsEkoMxKGdlRKijK3RgEUaP1vrE=,tag:DvaiGvjm9t2iS5hsrlh1aA==,type:str]
type: ENC[AES256_GCM,data:cbYQvNQn,iv:8WLgT6eiQDA8VCZd2+5JRdap7PvEemuNtEilimmmJ/8=,tag:mxoN8J7luIrjP+urXV/VqQ==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:0uYOr0ztCVgVXeMybTjcQ+dAmkMZ1F2YyXQg3E/wig9SSsXUbF7Sif8k3+TfEwnGSk0eQgnVTSzTJ6vUpcGrE5Ku9eKL8shV1u6aviWymwo04MV21zxDstDMOsZU1C6AOIg9VxaIeRoBeMbPYpwxCQ==,iv:mTI9DAEo8/95weBCxXiwzZrlWXnNLnbK2GiK7LmTPrw=,tag:9TJK2sm+EHErMS7HapWbLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzg5MFFNQzhXMWdzVXQv
            RGNIQ1VLSkExOWRuZXpCRkhMQk9uUjJrQVVnCktjWDhoNGVVT21CNTNDS1ZGam1s
            L284NHZJTU9mWTFmVlA4cEQyWDVJbG8KLS0tIGdHRVBQblNvK3ZocWRPbWtRaTRl
            M0c3emtpam0wekZJN0VkaENhSXV1Y2cK/xc1c5nlf4NknIxaiMqxE+ygHLjvUnO7
            by8nwot5ZlxIqHu821ZAd+LM7NeXgYg1HZe0BiOx7WCxOePuj9NOYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T18:11:20Z"
    mac: ENC[AES256_GCM,data:ujjIxZ/Nr7z20wbZeQVMDNuzf/FkFbojGQMypBN6woSFj/T1MhgzOqM9XHjDzDllTT6mNIzQvP2OOvENyaJDlU9GPiI0BC6jNXTT8WQwqgboy1WGQrzhJh21cOc1C4xuPG7TrYrErbTDYksiraE6dq6AMb39fuGAyc9LvFuPYoI=,iv:Rg4v+i4Wm6UoMq7NfAaUR3HjoHF5NbK0B9/24UH3Xls=,tag:kpsgWqer7uEQ/MFGbxP71Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
