apiVersion: ENC[AES256_GCM,data:eb4=,iv:S7IXSm71f+Hd6wsIjhKRF6RpUosAYCQDIs1+t/XMX0Q=,tag:F2chHjqOynCYeus4iwReyg==,type:str]
kind: ENC[AES256_GCM,data:cMTlj88N,iv:7hk3Sx0hs/pqQ2R9sNWdri1AcsUOBcVviaFCKAa8Tg0=,tag:0XYG9Jm6IQHPwhDG3T6tjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ipfhKay3T4gy675od9Ggo91Q,iv:sxYndcWkx70K1VmJd8nogLeKWIGbxz4n3wT/vkGrQz4=,tag:IeE+ir+H5D8pWfha82JeGA==,type:str]
    namespace: ENC[AES256_GCM,data:zYbQZ8rOxZfVJnk=,iv:TqGKGd5IOsYgO9vU6tNIhJc2u94j00li8GgtgbwncbI=,tag:7hYB2ue0x2ZJeSq7AgqAkw==,type:str]
type: ENC[AES256_GCM,data:HKgYxtXq,iv:9TZFf9aeuJlQQ1HYVJY50kUTIyRnIFCS+caGHZCWBKs=,tag:HgVVvWBuXXBuQk98RD8O1g==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ONaHz9ZdSBfVApA9JRR0dKDAl48=,iv:3FoArV5LOtvDStP/gqCxRrGa4C7yjn756mbOkO0+AsE=,tag:0oWh6lysnbE3vMCwpM2upw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BnBQrxwlz3fpkr2gL0aceqX5V58aKlpqe6dAWxFLLwtocJVi/oAAlA==,iv:tTmjhjBg7lzZWO/bnatoi6wKiAQwKl4sDlg+w/2Yoeo=,tag:lecoHH3v5DjFR5G+kOtukg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcEJwTWNHTWwwakF3MWlq
            UTJ2SW1PWUc5akdBQ1NlSkRQZkI5ekxwdFZBCnNMMGRzTW5TOGp3WmNRL05hc0xn
            TkROdXlrVUxRMVo5T3dHRUgxT0NGZjgKLS0tIElhTE9ncVpLbVk2cUlMOWpiQUlI
            Q0JxanYvaDJXNDZjMHJqS2FRdkVlZ0EKJNpLSwqYOnJUCwRgSPFPjZsGOyDNvKf/
            cmwddFUYx62lhWOqFAqQAECPaxhKeGPi5Nek7GVQOeCLEJhsy/sgcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:19Z"
    mac: ENC[AES256_GCM,data:gn7e1q2oU/iMK3LsUhD5xWm0Uz3qWBZSovAfsfAgMVIuiEoT634uefqafNZQz0XlFmcNdwHyh62IWIZ5FuakGUU6MmJmj4HmhlnwVC0AbD9JKSbzDlnUaVC04pCjPa2V8RTgxPoO1c8RUZijF/y2xzLDnizkVbm3wbEDFHFQP5A=,iv:ip0xDyhy+Koq4Xd8Vb2tJCIzreOKcckymwxSbh3q1IE=,tag:vwIxQluRI+/gfnn6unP7ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
