apiVersion: ENC[AES256_GCM,data:eb4=,iv:S7IXSm71f+Hd6wsIjhKRF6RpUosAYCQDIs1+t/XMX0Q=,tag:F2chHjqOynCYeus4iwReyg==,type:str]
kind: ENC[AES256_GCM,data:cMTlj88N,iv:7hk3Sx0hs/pqQ2R9sNWdri1AcsUOBcVviaFCKAa8Tg0=,tag:0XYG9Jm6IQHPwhDG3T6tjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ipfhKay3T4gy675od9Ggo91Q,iv:sxYndcWkx70K1VmJd8nogLeKWIGbxz4n3wT/vkGrQz4=,tag:IeE+ir+H5D8pWfha82JeGA==,type:str]
    namespace: ENC[AES256_GCM,data:zYbQZ8rOxZfVJnk=,iv:TqGKGd5IOsYgO9vU6tNIhJc2u94j00li8GgtgbwncbI=,tag:7hYB2ue0x2ZJeSq7AgqAkw==,type:str]
type: ENC[AES256_GCM,data:HKgYxtXq,iv:9TZFf9aeuJlQQ1HYVJY50kUTIyRnIFCS+caGHZCWBKs=,tag:HgVVvWBuXXBuQk98RD8O1g==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:K5CBXyW+HLX+gBCvZivxa8cCcqbjvWxGcLDvem0K,iv:2H+dHuqgPQ/Dhyw3CLMVXvXnOvZaezVXyh7mH6ozevw=,tag:TLbVvWUJWtBADa2dL6gGcw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a0f7NaVp655ZGch48R0zuryeEeK6TD9Bb+Rn4E9o,iv:1v3nujQz4P4+WE5c3/tPBn0pfdmOqIMQal3knJVCTZo=,tag:vyfRFbSO+KJeB1NCthbQHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcEJwTWNHTWwwakF3MWlq
            UTJ2SW1PWUc5akdBQ1NlSkRQZkI5ekxwdFZBCnNMMGRzTW5TOGp3WmNRL05hc0xn
            TkROdXlrVUxRMVo5T3dHRUgxT0NGZjgKLS0tIElhTE9ncVpLbVk2cUlMOWpiQUlI
            Q0JxanYvaDJXNDZjMHJqS2FRdkVlZ0EKJNpLSwqYOnJUCwRgSPFPjZsGOyDNvKf/
            cmwddFUYx62lhWOqFAqQAECPaxhKeGPi5Nek7GVQOeCLEJhsy/sgcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T18:32:26Z"
    mac: ENC[AES256_GCM,data:V55y9N4WNJj0S2a5ijFcsxykJmxAOMzIpLqJ01GiyszIlvTFbBzRRjqUtpCGwThUP5aAm5Qh/9l0UqKcfEeDibYyPSEDGKeakxW8+SjhuD657vf3YUQ3dQOp5AQ0TAiTHlyqsFbQ5bMYHOWlG9UffDucj6nwd6UTw2MEsIhbboM=,iv:kLOORuBEspY8bfogGk8vPv5SxweISBlwH9oB8q13NN8=,tag:jrbLK4RGQCsI/NcCR2Dffg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
