apiVersion: ENC[AES256_GCM,data:+JA=,iv:f0IUQjtb1o05SGDl24ByVz9iDgz0MVHeVJ06zAT1pe8=,tag:zV/M11F/Ub+MWnBaoHJPKg==,type:str]
kind: ENC[AES256_GCM,data:5tVcjTqK,iv:apdQLmcAvHuhHor+eA3QjAyqnzV0cZ5Ibr/Q9A3NlgY=,tag:Q9uzf+8oJ8wEoMnaxj1DxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zCm96QRyUN1XKILSogpk2OjyRgvhguk=,iv:HNNTSXyMcP05OFXpQqH0/Y/S1WcdJRumd0BVDRhYicU=,tag:ecgpfEqufTftTZFS6ywkXw==,type:str]
    namespace: ENC[AES256_GCM,data:bFHk2aGiygrtMz0=,iv:xh/lVBDkoUf1bcRTuu6zDfxS9M5o1tS2Yx3JCcfbjfU=,tag:mgyV37FP2S/a1tF1mIZNTQ==,type:str]
type: ENC[AES256_GCM,data:QGWldJKY,iv:S5mvXmG2iqjeX11mpzFTVZjlZLhPhuyiNTSVfoR6n7o=,tag:WxB3kkE/N4EYNYcbKpqXyg==,type:str]
stringData:
    talosconfig: ENC[AES256_GCM,data:XNA5OXUpvdBDaPYkWAp/rfodIQkk5tqMTe3OyNhdxiA=,iv:4YS6Cxd+jzKs7RGoRyGbLyY+WKQEg5UtNGsmm1RZmD4=,tag:uCeW0G/rXfEdkzqde41N0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGNKUmM5R3d3a0RDQUtu
            NkFsR05CbFdFVUxOQ0tqU3ZxQ1RleTU5QzJFCkRjRlhVNmJxSnNOL1NaczNQTzlC
            Rlo4K2hkMHlCNERIMUJCblRGaFdTUmMKLS0tIDJtWloxU1JPK3o5Y0FGbnJHZjZv
            a3Bpdi9ncEVVeFZBaUFiTlg5elgzNGcKVTGXXUis9BOK9djxARu6qnLj2cXCW3x1
            Qxw8R3ULyKTc0Pqsj+/lKLu69PAoyMH9y94+WEyU99aNkfoLypIo8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T18:32:26Z"
    mac: ENC[AES256_GCM,data:YVOKcyQ0wV/gWv5VqIyA48ABJ4kNJG7iggHuOZPtPHRioNAucwFgSpgg14ghFQB0Nebl05baMJL6ybQSWiNLFs34CRfFssLIH05qQFxi1WdJT/Y/mO/eAtC8PDjUrYp5H33m9zTu6bwkdYGiZYJBrshcHyhIfJk5mIKR7x5R6fQ=,iv:TTIt7QqgAE2wFzMClDfXxL8NLz99UazO9HQh4BztMT8=,tag:9brlIM9Gl0s+ZNdD0qqD+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
