apiVersion: ENC[AES256_GCM,data:BJM=,iv:XNNwAnaR8K3L0EXzhqeR1sui7KxsqJpW25J5VngBXQM=,tag:pjDace5DVsi9yCB6qKXhRw==,type:str]
kind: ENC[AES256_GCM,data:gN1eXl02,iv:gSiEELSwUOm6sq4uYTVKDFMbIsNUAx7LFBGcl92off0=,tag:FUVw7J9jsoQ1u68L5zXgYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WKINLUQPgTN84XLwWjM=,iv:e4b8uQ1j1A6gF0wu7goFeJXIck0CrR0WGZfpgyW5MQQ=,tag:7H+o3AH2rcMfZOGMfJ4X4g==,type:str]
    namespace: ENC[AES256_GCM,data:C+QVT+Qr,iv:5b+07BR2mLhF2msmSrSAkp0Buk6ewlZv8AjvaFJvSDg=,tag:5ap/Hp7km5Zq3xXxRkhO5A==,type:str]
type: ENC[AES256_GCM,data:AE2CFjad,iv:7McGB/5nAMZREUnMzJwD9V2ZDGjqWwSmxrzBPmQtF4A=,tag:vxuVnecxv/k+0w/DSEBA+w==,type:str]
stringData:
    secret_key: ENC[AES256_GCM,data:4HyACLodFqDO4ucmZ7DV2klyf6I0/6nvXuIi5HCnJYiEvaaIC5P2ZujUgQ+V1EBiz09YpvtLSPLHcrkFAyZzAq3KfLfBwWGmZprM4SmGllk=,iv:6yM9HOnXbcoZPElXRtgTmdYILJRG92qsghvPCC5pvPo=,tag:W81ULdqDoRAgQxOxhAzb+g==,type:str]
    email_password: ""
    api_token_peppers: ENC[AES256_GCM,data:Z6oZ9cHlnzISM1mGmtlcEjNQaG4kcVo1YSEmMF0Ybhm7ydgrH8JPXotC21aWWmC8ted+qh/3oJ1wc6EwNm6t7qZnnmeDOWb3nw==,iv:A26ZAY5FLOjxVgGpsoOQ1Ch2hqM7FJuLKg2VA9RIImo=,tag:/Y/nU8Ali+Lu9nElRnx0tQ==,type:str]
    username: ENC[AES256_GCM,data:qSvKr0w=,iv:T5Ng5Fa7wjoYU8UqhsNLMopXvGJ4WuRqq6kvN4QvSkM=,tag:jwjREd3gJRL5nbYxr8Umlw==,type:str]
    password: ENC[AES256_GCM,data:UyKTPeBMkMwvRPnZ8AtqwxGta57hb2Lu,iv:Q0HJ9tkIkFzruNZpWLhaoAhe2erY+bqnP1ZEMLRV0pc=,tag:h1uuhzoQK4dkk+nWLUTesA==,type:str]
    email: ENC[AES256_GCM,data:XH59KmuOSTMdtoj/t4u0blx2kOfIRryJNw==,iv:MGR0AicrTRWOLd6i2F0vJxtaKl7oXA9YiIRNmMV5l3g=,tag:diSuuz1XwyT5eN+3fnmYGQ==,type:str]
    api_token: ENC[AES256_GCM,data:aCB8tFT/30DrOotnI2mfMVehnKqu0T3QQYSJ2xy8HetMio5O1/p84w==,iv:QdUAhKJM7mLqB5aqs7YI4cnqmOUWaax1E97vxd2GbyA=,tag:NR1xTT65HMo1ekn7JBScPA==,type:str]
    postgresql-password: ENC[AES256_GCM,data:xqubYc/VShix66c//0rweaV49uKLIWeBJMayxF3bFa0=,iv:QGKYpK419a7Fkvni1NYnDDLzrLbm6KEpCBShnYEPbj8=,tag:/MOtRo05MRFC+ALzNgNm8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY1EvelFlc0Mzc1poZ3hM
            R3ZBNWlPQzU0MHVnWFB0VUV3YUpQMnAxWml3CmlmUWNVZXRuUWx6VXlmNVg1YnFV
            Ulptai9uaUxpQ1o4enpqUTh3SU5JNmMKLS0tIERVMUYzcUZmT0dXeXBLV05EMVpG
            eHVIZHc4bFhCemFFc1lRbGZHWDVEWlEKc55v/mQfYgs7EKZcdMm4biKkiY2zk7e1
            olxddt0W9KPYCDzoCCxYLI/TQKvrrbEH3YSTYtAGH/POYaf8afdh2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-09T21:16:39Z"
    mac: ENC[AES256_GCM,data:LcQx2U4NNXpcJjBA+rjMJvab/DfElf+ZlmXrIAN2wqumlHvPDGLoSX2CfDSJ4bl57/43Viil4zcYx/mn1Ikk53KDEpkphH9woMGR5clJCYd8v2o5BGrULNnn7pEXLAS30QRXh0ToAXuQmCByZC45LeGAEijFFwFA/oepzKEeXB0=,iv:9b1cpy2OcxwavSzTXf/Kj/4mx01+h3CNy7Wpy/VXyKA=,tag:RC555WHqFO/pEHtuSkZUyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
