apiVersion: ENC[AES256_GCM,data:C1Y=,iv:mxdseZNp7x2u3124b9cVvCaE/C6Kfs/MHfDSjYniaU0=,tag:r2Hp4vNN6CIGx4CBKhyarQ==,type:str]
kind: ENC[AES256_GCM,data:1xQzX8ry,iv:PVVrXQ8AISX0eVcev/WwV80TqwCXNMX6+D5YPmDOgro=,tag:/YMVI8tg9V9zzxnkjLjLLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:keYLOsQEj6tgmjviC2ZpqTeZ+9nuNf3n8YI=,iv:0d3Q4ZfksyGQRwWEkyoIF+DYCluPpcVY6G+ezOaVQvc=,tag:fLeCZpFC7PWj9iSdBtETMQ==,type:str]
    namespace: ENC[AES256_GCM,data:8tl5TXFy3RHS4H7rZZLU,iv:AQ6XAdiuwyaedJ2VxZMvlJA6Kyht1kgNnmdu1I43j+k=,tag:A1fOZqb2mL13gTSiudT14w==,type:str]
type: ENC[AES256_GCM,data:mpJSv2wM,iv:L9+A5jtOJDroVnZf2Y+BTYaWDK9mThelFBIDqXLzFtg=,tag:Y0yF6FbtcN5Oqc38EubN+g==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uUBMG3Ybfb1Sv7dwLqaYvQlV6bbArRyMozf07YpV,iv:1z2PIsDuSdCBu5Na9k0FdPoyuS3Cg7NTuq11P3tHPn0=,tag:y+hZb90ODA7Ta/S+SsNWYw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZVcYanFiaWEugXUEH2LT+zfC3Qeaufwts2hste6w,iv:qb2C7tZELbFu7uDiIGVKuJoP4hbu+zo8eEWmuEozy2U=,tag:f8qjU2wVONGzq1PYIgnUmA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:UNTkz3aeZG+1xCi0uvWOacPFraMYCgYl7bhw8b2QP2j32w==,iv:fldX7eiiLG7bwN9tRzBfRCEHAFFZ4Z/bAfzs4jqbDMo=,tag:DefU76DchViKQEDGqQH2Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdXhIME85eitNbS9TQlp0
            OHJDOUxpSDkwd3ZibXcwdkc2bXgvdjhmbDFvCjJHd0RYMDJCb0pKajN2UE9QbllO
            aTA4aU5pMnJOUjRKNmhnUU82WmJWSzQKLS0tIDRmTVl1SjRYemVEK3g1d1ppWXlB
            Q1k4ejh2VGFoYVYvVUt5U0NYQnV4SWsKI0lAROk7mda/FoCWaoqOPuV48vqoPwZg
            WQzjugGypl6AAuY5bRrO6VdO6lz/ITu18f66SvULOmOJRiDnAs0ZeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T16:24:59Z"
    mac: ENC[AES256_GCM,data:+E9uRiUc0wn+9yTtUDiilh4TXQdmnobOUgNSDZqhhE1KAzhmKHV9LtFItq2ei0n1Mg0Bq8x4ivl3JHq6D2G+SDdkS2BFknHi6I1lovCZk+GwvoiUqE5tbW4sB4tg3/c85YdRuCtufPYzD1hTGrR8kXD7rpmmOWpdV8kFzK/fpvw=,iv:PYOglfTxUqRXd3XUbPqINHjSrYeOePxCWlY/Fcl9XXo=,tag:K/hjBi1+Oo6epVtZ/WxOGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
