apiVersion: ENC[AES256_GCM,data:C1Y=,iv:mxdseZNp7x2u3124b9cVvCaE/C6Kfs/MHfDSjYniaU0=,tag:r2Hp4vNN6CIGx4CBKhyarQ==,type:str]
kind: ENC[AES256_GCM,data:1xQzX8ry,iv:PVVrXQ8AISX0eVcev/WwV80TqwCXNMX6+D5YPmDOgro=,tag:/YMVI8tg9V9zzxnkjLjLLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:keYLOsQEj6tgmjviC2ZpqTeZ+9nuNf3n8YI=,iv:0d3Q4ZfksyGQRwWEkyoIF+DYCluPpcVY6G+ezOaVQvc=,tag:fLeCZpFC7PWj9iSdBtETMQ==,type:str]
    namespace: ENC[AES256_GCM,data:8tl5TXFy3RHS4H7rZZLU,iv:AQ6XAdiuwyaedJ2VxZMvlJA6Kyht1kgNnmdu1I43j+k=,tag:A1fOZqb2mL13gTSiudT14w==,type:str]
type: ENC[AES256_GCM,data:mpJSv2wM,iv:L9+A5jtOJDroVnZf2Y+BTYaWDK9mThelFBIDqXLzFtg=,tag:Y0yF6FbtcN5Oqc38EubN+g==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pOcNz9y0Pdi1a3qBMN48ppNh+CI=,iv:4XEHKXfMCaGRoK7rVasMqkrPlHYss0HZ78izcYvjBnc=,tag:Wi0gb6TJ8BHt6pYJfopOFw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DIasUsBTANfNE/3K3faXjY6AUdhPCwrtRGvKPsru0Pez55CA6jgAfQ==,iv:nISIjTYEROxBDn9219Pa8K9A9YirVhFRqEF4oc/gfMk=,tag:dREQWcD6BL2UrW4k9Y6/1g==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:UNTkz3aeZG+1xCi0uvWOacPFraMYCgYl7bhw8b2QP2j32w==,iv:fldX7eiiLG7bwN9tRzBfRCEHAFFZ4Z/bAfzs4jqbDMo=,tag:DefU76DchViKQEDGqQH2Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdXhIME85eitNbS9TQlp0
            OHJDOUxpSDkwd3ZibXcwdkc2bXgvdjhmbDFvCjJHd0RYMDJCb0pKajN2UE9QbllO
            aTA4aU5pMnJOUjRKNmhnUU82WmJWSzQKLS0tIDRmTVl1SjRYemVEK3g1d1ppWXlB
            Q1k4ejh2VGFoYVYvVUt5U0NYQnV4SWsKI0lAROk7mda/FoCWaoqOPuV48vqoPwZg
            WQzjugGypl6AAuY5bRrO6VdO6lz/ITu18f66SvULOmOJRiDnAs0ZeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:17Z"
    mac: ENC[AES256_GCM,data:JRkbdZpR9KmWLgVrBRajp9fjvx7Tmy42dmrZcnBw0cH1ujQxW79IaQi5YsI+vXfzt82rpWKkJAQuoPVJpZ2HZGAIzlQESeHCmJgsizSHqOFA0ZXDK2/nO9VupWOoyaVvhUaXii4HQyb/APry+7CBXztywwNdwUWFGr74snYJ1P4=,iv:Ed0a1Ik9zaBgwNlVSSob2b19q9v7j+AVpfg2QH4m3lU=,tag:G6mq960RVGcEPzfJtl6J9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
