apiVersion: ENC[AES256_GCM,data:phI=,iv:6qx91VIqDodizbvAHm4Cuvlxk5JIS6IbMWFvDz+OEu0=,tag:QJOnCBToXWjBB76le+4qVA==,type:str]
kind: ENC[AES256_GCM,data:psGKmjRv,iv:aK/FfvrQPM+WK26oA/fAUA1IJlsbp9q5hrb7ZxbtKu0=,tag:ZzFIwQmuUi6FmRTGhgoaKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8MmlOUbkMaj3Djk+RCYxOBc=,iv:A4PqJ7Q3Hh3corTdVTogGgQr+bVbcSzhdRz/d0hdLCs=,tag:IivtMuyVyTUgEvUR1TMGpw==,type:str]
    namespace: ENC[AES256_GCM,data:c04t2DbGhb+Y,iv:CJrq8iql/Ny2+K3OUj8IeJxe2H5Q+X6QdaMr2vbvZkI=,tag:XDgufUztOMIqE3QOHjps8w==,type:str]
type: ENC[AES256_GCM,data:DSsQhfijIwskS1wZ7ePYq3YPtMNKhBYo,iv:1uHnPUwB8YzpH85j2ruQ743Qyqz5pB5Pn/gOji9dv3s=,tag:iBwmABKScUlHWDotUGXRDg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:QViuHMt2UVNK,iv:d0ZbHPjNQWLaKm+4YRsTU1BrEkJ9EIFy6Tq1RAURXow=,tag:4aY7K9wtrAnVm3RXsGQXGg==,type:str]
    password: ENC[AES256_GCM,data:/fJPADcroKV68XQtGZcTvUSQSWbEN0K8cCGbY0+fg4bryI1KnfJOvPM3O7uYEKQ19rrQcvh+XTGvZfXt52Rq+g==,iv:z9zWBNIHFJ17bM8krFgRn693e/OQ49+NXYPZFC2+8Zo=,tag:phZDH7lsPwwa/a54ZTW7SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT0J2WENpSFlqY0NMcThH
            RDMzQ3VSZVhPT0lweFYwY1N3aFM4WjV6RVYwCnJFSk5nZFc0TVRaRjB4ZjZKM0pP
            MG94NDlJMk9JQ2k2L3ZJNnhkZS9pWHMKLS0tIEgwUTNuMmhLbHFoRUw1MTVrd2dU
            Qkpxd0NWWU5iQlNkS2RpM2FtSHBqbFEKe7Bdn/two4r/oH7o76s2+0Hi7ejgKCMC
            ntzTAs+/02un6e7FGXQS6SqaCIuqAC32qkfyoSHejZqoc4VMcvnhlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:18Z"
    mac: ENC[AES256_GCM,data:3uS7tu4n3RMp1EFJsgQL5PziScyTGi4rXajpu9zLpxaKpBXpAGu5qs7cYAKwPM33iGkMfFugX5TPHKEtx1Jpcw9zGHmB27mxgg9bvoMFbmbVZI2PicJ+Qz/5I+cJPr8OK74ScebtxG5euqkeMnJn2SZFA3ASYZIjbfNXNGwzm8o=,iv:g2+Jb3nrYJ769G1SA+yo2RBn9gYc0dVAO7HkRpqvL5I=,tag:afWgwRmghEzfnfTlAZDG3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
