apiVersion: ENC[AES256_GCM,data:b3c=,iv:+3nBqaqRB4Yq4FTnnxDbJ1sq8Ey+w9iPP3gPyP/dTCg=,tag:7g73qdfMzhlhQT25hDhvNQ==,type:str]
kind: ENC[AES256_GCM,data:ZO+k1zr7,iv:UW466yn8f1FyViWjtbkUvY0zHTAMiPLEm1hg4h8wbG8=,tag:XXXi34tSiNtlTULpKlAjww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gm2O+SLaaeBDS1QTXJQ/vFVuNNtWLQ==,iv:hxt3Zpmk6O/SENavTn4MKqUW1NGjFgbjF9F+w9VBenI=,tag:NQAyLt1wmW6BNxI4oaBjzg==,type:str]
    namespace: ENC[AES256_GCM,data:6q5muJG9Uxui,iv:uJ38xF04oOSgEPRb5NS64a32z4Ovff9+9uz1D8lOb8E=,tag:1VxF92IPMCXQXkJWh/hAVw==,type:str]
type: ENC[AES256_GCM,data:DvOLn3t7,iv:p2y2YklNbEIjmOo6RtczPXEwfEh/G8pMez/MqCqafqs=,tag:3N5+q3AnhPR6ie3hB0ZdXw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:70GiQBkUz34VB7xeFFQn40kEdr4=,iv:4LTZE4+9i1dskRUF/9kemfsnLg+Db5Xsm39ZzD4J5zI=,tag:5ZtZdmaZrbR4d6A05Qj9Ag==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:aF/fSsmrg3a/8eLzAp0aETQBKoxlZ26f5ReD8GzDHoseMWy33OoMNA==,iv:KZmlrj+BEcaQvwf7dVdib8Fe1CWsW+rgOtVhBfy+J6E=,tag:upTHvfJBoL72zoawQIarWA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:t+AxFoFx4wB9,iv:X7aeNel8JIrfNrwxoQzfwjI/fym1zgUzreNRRUhOUcg=,tag:dAcOfAgfRN2zdIHTf192pA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGRtU0VxL0s5YWIzREpN
            MUREdnNPS29DYmF4OFYwbHlSUzdIYU1KY1RBCncvVGZwYjllWHRSanZLbmZNVWFp
            V09YY1p5RWk3RDBNT0tETzVPM3hDOEEKLS0tIHFvSWg5WWxwdlFOSm5oUzhhSWhh
            UEpJaXNTNFpUSUlMSEJzdERaV09mbk0KidKuvsujilI3k4BckC9upYrDixAioHnN
            fgo1KCd4EBb2Ndc1SwxbQ8NKpJ0bTU9qemBmzhrJdu7ZxmZF8SFInw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-04T19:19:18Z"
    mac: ENC[AES256_GCM,data:Sub32apkaD9k+R2omMHFGlB7UdXdvLkQ5yhDtQTQo9nuo1mm6vkTO4pJ4NmNodcTnF6ClREb9AZZ6RB+pQzQqxYXwsJjWOUV4Md7Ai8/P15DPMe/QR29f5RuW5MveUjjZAXJuIdxKaEfFl5GtGNvL9T6sATvtgVwn/CahXhtJEo=,iv:t5npY5TYUtfWUCCWCjBA0YISZpyIDAO+dhjMBhDCjUM=,tag:PIZN4KWdLewgQxOrqOPwkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
