apiVersion: ENC[AES256_GCM,data:qZ4=,iv:DrI1gpnw7D4dseio6IOXwC3uOj46mTUq09c5M1diZOI=,tag:e2StTenw6Zor2tgXQ2+dSA==,type:str]
kind: ENC[AES256_GCM,data:sLwnz8+N,iv:RER3hH2gahi2KIicULwWpEm3wa10i1730tO40XT383k=,tag:Ynp4Z9BtQqMkn7xFSlED3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Px16nlJd2aG4coetQOZ+,iv:2fWUndeNXqNlnmSrEdlyMEhp9TY+VfaW1iC9qJMdGmY=,tag:B/avl5FhohbT/NPFfRXJjQ==,type:str]
    namespace: ENC[AES256_GCM,data:1rhWmXcJiiB4,iv:XKLGO5FZPwnkXWSLBoL/YMj3EPbOKS74Qbn4uOdo3cE=,tag:4eyrSxrr29WuCDYaPY1MnQ==,type:str]
type: ENC[AES256_GCM,data:CHEfRwAAG3nWuyvfOSmaQQ+aR8syd+b7,iv:5PxCEqqQty56bgqZOCTa/z187pARs99DJ0rtcAFdY6o=,tag:TCGXgiHdUdmqv+sl4p8HVg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Uw5UpsINig==,iv:QXihE7EdYANPyFBMo6m7/CCeKr07uGjuQaRaKJqEgTw=,tag:8XXJah3JD7bUmu8ZAzcnKQ==,type:str]
    password: ENC[AES256_GCM,data:ZyWWXPWT8xv9JhvogXiRylmqoCPw5RH1+436P7a36w==,iv:hvwRl/gt66fx4XF88zOCOkkXoA9InGfARiauePd0hxA=,tag:Xf7WxAWDVXlSsSnWCmguww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVEk1UnhKaVpRVklmdzA5
            YlNmaFozZlN1aytJdDJlSTBuaVNGVmVoRURJCkpUcldObnJHS2RQeFZvSWkxL0w4
            cnIyQUc4b2xMdzRNSFZLYXpUbVJhZUEKLS0tIGxweExKRTRVOHBOalJnSVdjVUwr
            WWRqZ0FYTUdxT2xrMXllNDFYaFkvZWcKBLD8TlnWwiy1WT0ZaPuwsRNp2TPCdAmk
            H9ZNNfRQcraHdgtGtf28mod3RA3Kwkf+z7NHnv4L0VDl4KUsYui9ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-10T23:24:19Z"
    mac: ENC[AES256_GCM,data:8v8kiO/k+vwj0iQFxf2s/ouEGiS7y/uUxe+IY/vSiCnpClfERqRHXZ1A8HBIyUyUEvlNeOQGpVCfWpkwqpW6bAL0C2m/+2WugQNwL/QNGW1V1Pd5LbGhZKo/myNETfy6Az0fLWJ3R2A6W1ts1F7Gop8DhhK3SxHEmmkvaR/+XAA=,iv:SmvWzdqh1SZAln45yPmtLObuBaNFRKO9ILIU42FZ7Gg=,tag:Ezq0+z1snvF1X9lqI4T3kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
