apiVersion: ENC[AES256_GCM,data:XSo=,iv:h7Hy+ggPRhTSExvH4RTBKn+ot1R3WRJF5albtZI72nE=,tag:aiMFix+OMZXBY1kS2O2DNA==,type:str]
kind: ENC[AES256_GCM,data:9fTYWOB3,iv:ddUWgpXZcb/cGD4ccFJUhqI+ws1/Ipxa8gidwwJT1Rg=,tag:UDEqe3BVhlrPLI4kEZwVNQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sc0ie+ja6jmRkD+qJ8E=,iv:LBwiNfI+4OIuiAoPHjdNzUMJpS5FFHa9+5WaK8vuEUI=,tag:LsalOuCX51VvwvlbFrf3aA==,type:str]
    namespace: ENC[AES256_GCM,data:wp9hf/UqGJaB,iv:BZctFoUMUCSmntISs9LiUG5ISqcLgobp3CiCdUmcWvk=,tag:rrGhYIxgxZj3wiUVXfIKaA==,type:str]
type: ENC[AES256_GCM,data:kux4Jb7t+1n87W3p/m62ObMMwyGooqFz,iv:wnVNXpiHrz4JzLFxvcVpzRDXSARjtHVLWFz6kRtGAu0=,tag:gVZ3jCQpI6m7njehtJWVYg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:RhenSWS6,iv:5Afy6BNxoP/YVBsJPVsxHl5of9ElFCBkoKGxcVhMNSk=,tag:n6ETfSPfoDhOGwRdcyf20w==,type:str]
    password: ENC[AES256_GCM,data:43EDSlMdRehHEzwwfojIClQpQ1LMNt3Hz4AVY/KEbjE=,iv:nuA0vMKjLAtSfoy2/1XacYTGZ9domFF5QANn7X2M2zg=,tag:F1qhNysSAR7En0GtW0Sa0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFd4Z29Bci9nejlDdzdo
            c0dIcGhlN04zRG1qK0pzMmxtNDUxUTBQbUNBCk5QcGdkd0oydUZUWlQxbXY4Y0VR
            NUcrVVV1enBKQWZDMlQ3SjBYUEw4VDgKLS0tIFhKVHF3R25WWkVnRW82d05WVFZS
            MWNnWHdRZ2gwU2ljRFZ5cGFwUEZkSzQKJ1zMMkZWKXyjB1I3kzVTaKtUfMWQnUDV
            5is4PAD5/ZcA6GkpLCZD+D3N3Z3NjgMZbxdqIZTBzdYWE9yxrsegBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k70qedycqmleggtmwcuqwmkzrsldzrc4zxp0c4dymkuk240czsxskt3jfm
    lastmodified: "2026-06-09T21:05:50Z"
    mac: ENC[AES256_GCM,data:b8lYGZZl3u1+siMkUaX6yO8TBIj+YBNzDFCUL+8HRuXmYPCyEvzxESkLTXOE/v6tSh7ctJY2zxebR0xuUIBhk34YuuLOcpjns3jXHv5UgnNsvsCmuXUJsZxgapXdVgQ+9ATXwNVqOegxNiVeqJrIZZDMC/SCuE99FT0EZV9ShfQ=,iv:WFyPHZUScFZKZ4WF6pFKpu3gxDVdvnAOLpbsVMhcskE=,tag:XKPTD7Y+taBh9mT53756xA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
